<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LP-PC0MQFYK" name="SeleniumTest.Asserts" tests="1" failures="1" timestamp="10 Jul 2018 18:00:45 GMT" time="14.771" errors="0">
  <testcase name="f" time="14.771" classname="SeleniumTest.Asserts">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	*** Invalid Error Msg Displayed *** expected [Please enter your first name1] but found [[[ChromeDriver: chrome on XP (a68592e18cf723a12b152d12821bee28)] -&gt; xpath: //small[contains(text(),&#039;Please enter your first name&#039;)]]]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	*** Invalid Error Msg Displayed *** expected [Please enter your first name1] but found [[[ChromeDriver: chrome on XP (a68592e18cf723a12b152d12821bee28)] -> xpath: //small[contains(text(),'Please enter your first name')]]]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at SeleniumTest.Asserts.f(Asserts.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- SeleniumTest.Asserts -->
